scrape_configs:
  - job_name: api_metrics
    metrics_path: '/api/v1/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['moonkeyeu-core-api:8080', 'moonkeyeu-etl-api:8081']

  - job_name: mysql_exporter
    scrape_interval: 30s
    static_configs:
      - targets: ['mysql-exporter:9104']
