spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:${LOCAL_MYSQL_PORT}}/${MYSQL_DATABASE:${LOCAL_MYSQL_DATABASE}}
    username: ${MYSQL_USER:${LOCAL_MYSQL_USER}}
    password: ${MYSQL_PASSWORD:${LOCAL_MYSQL_PASSWORD}}
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        generate_statistics: false
        jdbc:
          batch_size: 500
      order_inserts: true
      order_updates: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

  codec:
    max-in-memory-size: 20MB

  main:
    allow-bean-definition-overriding: true

aws:
  region: ${S3_REGION}
  s3:
    buckets:
      db-images: ${S3_BUCKET}
      root: ${S3_BUCKET_ROOT}
  cloudfront:
    url: https://cdn.moonkeyeu.com/

application:
  backend:
    url: http://localhost:8080/api/v1/
  clean:
    root:
      data:
        folder: ${OUTPUT_CLEAN_DIR}
      images:
        folder: ${DB_IMAGES_DIR}
  raw:
    root:
      data:
        folder: ${INPUT_RAW_DIR}
  api:
    the-space-devs:
      url: https://ll.thespacedevs.com
      version: 2.3.0

management:
  endpoints:
    web:
      exposure:
        include: [ "health", "prometheus", "metrics" ]
  endpoint:
    health:
      show-details: always
      group:
        core-api:
          include: db
  health:
    db:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

server:
  port: 8081
  servlet:
    context-path: /api/v1/

logging:
  level:
    security:
      web: DEBUG
    org:
      springframework:
        jdbc:
          datasource:
            DriverManagerDataSource: DEBUG
      hibernate:
        SQL: off
        type:
          descriptor:
            sql:
              BasicBinder: off

